name: KeyLogger
options:
  bundleIdPrefix: com.keylogger
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.keylogger.app
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    INFOPLIST_FILE: KeyLogger/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    SWIFT_VERSION: 5.9
    
targets:
  KeyLogger:
    type: application
    platform: macOS
    sources:
      - path: KeyLogger
        excludes:
          - "*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.keylogger.app
        INFOPLIST_FILE: KeyLogger/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
    dependencies:
      - package: GRDB
        
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.24.0
